# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

export GIT_PS1_SHOWDIRTYSTATE=1
GIT_PROMPT_FILE=$HOME/.git-prompt.sh
if [[ -f $GIT_PROMPT_FILE ]]; then
    source $GIT_PROMPT_FILE
fi

function _update_ps1() {
    PS1="$(powerline-go -cwd-mode dironly -numeric-exit-codes -mode patched -modules "time,nix-shell,user,ssh,cwd,perms,git,jobs,exit,root" -shell bash -error $?)"
}

if [[ "$TERM" != "linux" ]] && command -v powerline-go &>/dev/null; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
