#!/usr/bin/env bash

SESSIONS=()
for s in $(tr : '\n' <<< "$XDG_DATA_DIRS"); do
    [[ -d $s/xsessions ]] || continue
    for i in $s/xsessions/*.desktop; do
        read -r __session < <(grep -Po '^Exec=\K.*' $i)
        SESSIONS+=("$__session")
    done
done

export QT_QPA_PLATFORM=xcb
systemctl --user import-environment \
    DBUS_SESSION_BUS_ADDRESS \
    DISPLAY \
    XAUTHORITY \
    PATH \
    NIX_PATH \
    QT_QPA_PLATFORM \
    XDG_{SESSION_{ID,TYPE},{DATA,CONFIG}_DIRS,{RUNTIME,DESKTOP_PORTAL}_DIR}

xhost si:localuser:$USER # for autosuspend

exec ${SESSIONS[0]}
